FROM amazonlinux:2023 AS base

# Establecer variables de entorno
ENV PYTHONUNBUFFERED=1 \
    PYTHONDONTWRITEBYTECODE=1 \
    PIP_NO_CACHE_DIR=1 \
    PIP_DISABLE_PIP_VERSION_CHECK=1

WORKDIR /code

RUN dnf update -y && \
    dnf install -y \
        python3.11 \
        python3.11-pip \
        python3.11-devel \
        gcc \
        gcc-c++ \
        git \
        tar \
        gzip \
        wget \
        make \
        which && \
    dnf clean all && \
    rm -rf /var/cache/dnf

RUN ln -sf /usr/bin/python3.11 /usr/bin/python3 && \
    ln -sf /usr/bin/python3.11 /usr/bin/python && \
    ln -sf /usr/bin/pip3.11 /usr/bin/pip3 && \
    ln -sf /usr/bin/pip3.11 /usr/bin/pip

RUN pip3 install --no-cache-dir --upgrade pip pipenv

FROM base AS builder
ENV PIPENV_VENV_IN_PROJECT=1

COPY local/workspace/Pipfile local/workspace/Pipfile.lock /code/
RUN pipenv install --deploy --ignore-pipfile

FROM base AS runner

RUN useradd -m -u 1000 -s /bin/bash glue_user && \
    mkdir -p /home/glue_user/.local /home/glue_user/workspace && \
    chown -R glue_user:glue_user /home/glue_user

RUN mkdir -p /home/glue_user/.jupyter && \
    echo "c.NotebookApp.token = ''" > /home/glue_user/.jupyter/jupyter_notebook_config.py && \
    echo "c.NotebookApp.password = ''" >> /home/glue_user/.jupyter/jupyter_notebook_config.py && \
    echo "c.NotebookApp.ip = '0.0.0.0'" >> /home/glue_user/.jupyter/jupyter_notebook_config.py && \
    echo "c.NotebookApp.notebook_dir = '/home/glue_user/workspace'" >> /home/glue_user/.jupyter/jupyter_notebook_config.py && \
    chown -R glue_user:glue_user /home/glue_user/.jupyter

COPY local/entrypoint.sh /usr/local/bin/
RUN chmod +x /usr/local/bin/entrypoint.sh && \
    chown glue_user:glue_user /usr/local/bin/entrypoint.sh

COPY --from=builder /code/.venv /home/glue_user/workspace/.venv
COPY local/workspace /home/glue_user/workspace

WORKDIR /home/glue_user/workspace
USER glue_user


ENV PATH="/home/glue_user/workspace/.venv/bin:/home/glue_user/.local/bin:${PATH}" \
    PYTHONPATH="/home/glue_user/workspace:${PYTHONPATH}"

EXPOSE 8888 4040

ENTRYPOINT ["/usr/local/bin/entrypoint.sh"]
