AWSTemplateFormatVersion: "2010-09-09"
Description: "AWS Glue Job for GTFS Data Processing with Nested Stacks"

Parameters:
  S3Bucket:
    Type: String
    Description: S3 Bucket for scripts and data
  S3BUCKETArtifactory:
    Type: String
    Description: S3 Bucket for artifactory resources
  GlueJobName:
    Type: String
  Environment:
    Type: String
  WorkerType:
    Type: String
  NumberOfWorkers:
    Type: String
  MaxConcurrentRuns:
    Type: Number
    Description: Maximum number of concurrent runs for Glue jobs
    Default: 25
  MaxConcurrentStateMachines:
    Type: Number
    Description: Maximum number of concurrent state machine executions
    Default: 5
  LambdaS3KeyPrefix:
    Type: String
    Description: S3 key prefix for Lambda function code packages
    Default: lambda

  PreProcessorLayerArn:
    Type: String
    Description: ARN for the pre_processor Lambda function layer
    Default: ""
  PandasLayerArn:
    Type: String
    Description: ARN de la capa de Pandas de AWS
    Default: "arn:aws:lambda:eu-west-1:336392948345:layer:AWSLambda-Python311-SciPy1x:1"


Resources:
  # Parámetros SSM para compartir valores entre stacks
  ParamStoreStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "https://${S3BUCKETArtifactory}.s3.amazonaws.com/cloudformation/nested-stacks/template-param-store.yaml"
      Parameters:
        Environment: !Ref Environment
      TimeoutInMinutes: 10

  # Stack de infraestructura base (DynamoDB tables)
  DynamoDBStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "https://${S3BUCKETArtifactory}.s3.amazonaws.com/cloudformation/nested-stacks/template-dynamo.yaml"
      Parameters:
        Environment: !Ref Environment
      TimeoutInMinutes: 10

  # Stack de funciones Lambda
  LambdaStack:
    Type: AWS::CloudFormation::Stack
    DependsOn:
      - DynamoDBStack
      - ParamStoreStack
    Properties:
      TemplateURL: !Sub "https://${S3BUCKETArtifactory}.s3.amazonaws.com/cloudformation/nested-stacks/template-lambda.yaml"
      Parameters:
        S3Bucket: !Ref S3Bucket
        Environment: !Ref Environment
        LambdaS3KeyPrefix: !Ref LambdaS3KeyPrefix
        ProcessingStateTableName: !GetAtt DynamoDBStack.Outputs.ProcessingStateTableName
        CapacityControlTableName: !GetAtt DynamoDBStack.Outputs.CapacityControlTableName
        MaxConcurrentStateMachines: !Ref MaxConcurrentStateMachines
        PreProcessorLayerArn: !Ref PreProcessorLayerArn
        PandasLayerArn: !Ref PandasLayerArn
        StateMachineArnParamName: !GetAtt ParamStoreStack.Outputs.StateMachineArnParameter
      TimeoutInMinutes: 15

  # Stack de trabajos Glue
  GlueStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: DynamoDBStack
    Properties:
      TemplateURL: !Sub "https://${S3BUCKETArtifactory}.s3.amazonaws.com/cloudformation/nested-stacks/template-glue.yaml"
      Parameters:
        S3Bucket: !Ref S3Bucket
        S3BUCKETArtifactory: !Ref S3BUCKETArtifactory
        Environment: !Ref Environment
        WorkerType: !Ref WorkerType
        NumberOfWorkers: !Ref NumberOfWorkers
        MaxConcurrentRuns: !Ref MaxConcurrentRuns
        GlueJobName: !Ref GlueJobName
      TimeoutInMinutes: 15

  # Stack de Step Functions
  StepFunctionsStack:
    Type: AWS::CloudFormation::Stack
    DependsOn:
      - LambdaStack
      - GlueStack
      - ParamStoreStack
    Properties:
      TemplateURL: !Sub "https://${S3BUCKETArtifactory}.s3.amazonaws.com/cloudformation/nested-stacks/template-step-functions.yaml"
      Parameters:
        Environment: !Ref Environment
        S3Bucket: !Ref S3Bucket
        GTFSPreprocessorFunction: !GetAtt LambdaStack.Outputs.GTFSPreprocessorFunction
        CheckCapacityFunction: !GetAtt LambdaStack.Outputs.CheckCapacityFunction
        ReleaseCapacityFunction: !GetAtt LambdaStack.Outputs.ReleaseCapacityFunction
        TriggerNextExecutionFunction: !GetAtt LambdaStack.Outputs.TriggerNextExecutionFunction
        MacroGeneratorJob: !GetAtt GlueStack.Outputs.MacroGeneratorJob
        MacroStopsGeneratorJob: !GetAtt GlueStack.Outputs.MacroStopsGeneratorJob
        ProcessingStateTableName: !GetAtt DynamoDBStack.Outputs.ProcessingStateTableName
        StateMachineArnParamName: !GetAtt ParamStoreStack.Outputs.StateMachineArnParameter
        StateMachineUpdaterFunctionName: !GetAtt LambdaStack.Outputs.StateMachineUpdaterFunction
      TimeoutInMinutes: 15

Outputs:
  # Outputs consolidados de los stacks anidados
  GTFSPreprocessorFunction:
    Description: Name of the GTFS Preprocessor Lambda function
    Value: !GetAtt LambdaStack.Outputs.GTFSPreprocessorFunction
  MacroGeneratorJob:
    Description: Name of the Macro Generator Glue job
    Value: !GetAtt GlueStack.Outputs.MacroGeneratorJob
  MacroStopsGeneratorJob:
    Description: Name of the Macro Stops Generator Glue job
    Value: !GetAtt GlueStack.Outputs.MacroStopsGeneratorJob
  GlueJobRole:
    Description: IAM Role for Glue jobs
    Value: !GetAtt GlueStack.Outputs.GlueJobRole
  StateMachine:
    Description: ARN of the Step Functions state machine
    Value: !GetAtt StepFunctionsStack.Outputs.StateMachine
  ProcessingStateTable:
    Description: Name of the DynamoDB table for processing state
    Value: !GetAtt DynamoDBStack.Outputs.ProcessingStateTableName
  CapacityControlTable:
    Description: Name of the DynamoDB table for capacity control
    Value: !GetAtt DynamoDBStack.Outputs.CapacityControlTableName
  MaxConcurrentRuns:
    Description: Maximum number of concurrent runs for Glue jobs
    Value: !Ref MaxConcurrentRuns
  MaxConcurrentStateMachines:
    Description: Maximum number of concurrent state machine executions
    Value: !Ref MaxConcurrentStateMachines
